[package]
name = "zoneinfo_parse"
version = "0.1.0"
authors = ["Ben S <ogham@bsago.me>"]

[dependencies]
lazy_static = "*"
regex = "*"

[dependencies.datetime]
git = "https://github.com/rust-datetime/datetime.git"
